name: CI/CD PIPELINE TO BULD AND DEPLOY TO TOMCAT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV-ENV

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: validate with maven 
        run:  mvn validate
      - name: compile with maven
        run:   mvn compile 
      - name:  test with maven
        run:  mvn test
      - name: package with maven
        run:  mvn package
      - name: verify war file
        run: ls -lh target/ 
        
      - name: Deploy WAR to Tomcat
        run: |
           curl -v \
           -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
           -T target/petclinic.war \
            "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/petclinic&update=true"  
